version: '3.7'

services:
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  django:
    build: .
    image: 'websource'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DEBUG=True
      - PORT=9000
    ports:
      - 8000:9000
    depends_on:
      - postgres
volumes:
  postgres_data: