# Generated by Django 2.2.5 on 2019-09-05 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('perfil_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premio', models.CharField(max_length=1024)),
                ('post_instagram', models.CharField(max_length=1024)),
                ('perfil_instagram', models.CharField(max_length=1024)),
                ('inscritos', models.ManyToManyField(to='sorteio.Pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
