# Generated by Django 2.2.5 on 2019-09-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='vencedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorteios_vencidos', to='sorteio.Pessoa'),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='vencedor_unico',
            field=models.BooleanField(default=False),
        ),
    ]
