# Generated by Django 2.2.5 on 2019-09-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_auto_20190905_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='perfil_instagram',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='post_instagram',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='vencedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorteios_vencidos', to='sorteio.Pessoa'),
        ),
    ]
