name: Docker Image CI

on:
  push:
    branches:        
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a custom command
      uses: actions/gcloud/auth@master
      with:
        secrets: "GCLOUD_AUTH"
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag gcr.io/campusparty2019/djangoapp
        gcloud auth configure-docker
        docker push gcr.io/campusparty2019/djangoapp
